from helper import DBinit

DATABASE = 'CA_COACH_PENSION'

sql = f'''
  DROP DATABASE IF EXISTS {DATABASE};
  CREATE DATABASE {DATABASE};
  USE {DATABASE};
  CREATE TABLE T_PERSON (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) UNIQUE
  );
  CREATE TABLE T_EMPLOYER (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) UNIQUE
  );
  CREATE TABLE T_EMPLOYMENT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(64),
    PERSON_ID INT,
    EMPLOYER_ID INT,
    UNIQUE KEY (PERSON_ID, EMPLOYER_ID, TITLE)
  );
  CREATE TABLE T_PENSION (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) UNIQUE
  );
  CREATE TABLE T_PENSION_DETAIL (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMPLOYMENT_ID INT,
    PENSION_ID INT,
    PENSION_VALUE INT,
    YEARS_OF_SERVICE NUMERIC,
    YEAR_OF_RETIREMENT INT
  );
'''
DBinit(DATABASE, sql)